### ISSUE TITLE
Cannot get a STRING value from a NUMERIC cell

### ISSUE THREAD

**Issue by 18916204759** [xuxueli/xxl-tool#4]
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell
	at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:1077)
	at org.apache.poi.xssf.usermodel.XSSFCell.getRichStringCellValue(XSSFCell.java:395)
	at org.apache.poi.xssf.usermodel.XSSFCell.getStringCellValue(XSSFCell.java:347)
	at com.xuxueli.poi.excel.ExcelImportUtil.importExcel(ExcelImportUtil.java:70)
	at com.xuxueli.poi.excel.ExcelImportUtil.importExcel(ExcelImportUtil.java:135)

**Comment by rajbhandarisubodh** [comment]
The cell has interger value so you need to getNemericCellValue();
For example: sheet.getRow(<rowNumber>).getCell(<cellNumber>).getNumericCellValue();

**Comment by zoransi** [comment]
switch(cell){
                    case NUMERIC:
                        intVal = row.getCell(j).getNumericCellValue();
                        System.out.print(intVal);
                        break;
                    case STRING:
                        stringVal = row.getCell(j).getStringCellValue();
                        System.out.print(stringVal);
                        break;
}

**Comment by xuxueli** [comment]
Thank you for your feedback. We have optimized the support
